server:
  port: 18080

spring:
  application:
    name: loong-ai-diagnosis
  config:
    import:
      - classpath:diagnosis-core.yml
      - classpath:diagnosis-rules.yml
  ai:
    zhipuai:
      api-key: ${LLM_API_KEY:a8d7009ef16942cd81bf9c5e4aca4ea7.BYPjEQKRV0gD98yC}
      chat:
        options:
          model: ${LLM_MODEL:glm-4.7-flash}
          temperature: 0.1
    retry:
      max-attempts: 2
      backoff:
        initial-interval: 1s
        multiplier: 2
        max-interval: 5s

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

spring.web.resources:
  cache:
    period: 0
    cachecontrol:
      no-cache: true
      no-store: true
